### ISSUE TITLE
Unable to build docs: missing dependency

### ISSUE THREAD

**Issue by gvwilson** [poissonconsulting/checkr#10]
1.  Fork the `checkr` repository.
2.  Open the `.Rproj` file with RStudio.
3.  Run `devtools::document()`.
        Updating checkr documentation
        Loading checkr
        Error in (function (dep_name, dep_ver = NA, dep_compare = NA)  : 
          Dependency package err not available.
4.  Try `install.packages("err")`
        Warning in install.packages :
          package 'err' is not available (for R version 3.5.1)
5.  Hunt around until I find Poisson Consulting's `err` package and run `devtools::install_github("poissonconsulting/err")`, after which I can rebuild documentation.

**Comment by joethorley** [comment]
@gvwilson - thanks for flagging  that up

I've updated the installations instructions of the Readme to to avoid this issue

```
install.packages("drat")
drat::addRepo("poissonconsulting")
install.packages("devtools")
devtools::install_github("poissonconsulting/checkr")
```

https://github.com/poissonconsulting/checkr
