### ISSUE TITLE
check_data with units

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/checkr#3]
When column is of class units, I have been doing:
```
check_data(ef_visit %>% mutate(WettedWidth = as.numeric(WettedWidth)), values = list(
  Date = Sys.Date(),
  EFSite = factor(""),
  WettedWidth = c(5, 30),
  Passes = 1:3
))
```
This gets a little cumbersome when many columns have units. Perhaps check_data could automatically convert units variables to integer or numeric?

**Comment by joethorley** [comment]
This is an excellent idea!!

I'll get on it when I have some time

**Comment by joethorley** [comment]
Its kind of cool but checkr already works perfectly if one sets the values to be units (of the correct type) which on reflection I think is the correct behaviour
```

> data <- data.frame(ColA = units::set_units(1:10, "m"))
> check_data(data, values = list(ColA = c(1, 10)))
 Show Traceback
 
 Rerun with Debug
 Error: column ColA of data must be class numeric > check_data(data, values = list(ColA = units::set_units(c(1,10), "m")))
> check_data(data, values = list(ColA = units::set_units(c(1,10), "km")))
 Show Traceback
 
 Rerun with Debug
 Error: the values in column ColA of data must lie between 1 and 10 > check_data(data, values = list(ColA = units::set_units(c(1/1000,10/1000), "km")))```

**Comment by sebdalgarno** [comment]
makes sense. better to force the user to acknowledge they are feeding units into the function
