### ISSUE TITLE
check_list with named = TRUE

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/checkr#4]
I would like to check that ALL elements of a list are named.
If I do:
```
l <- list(a = data.frame(a = 1), data.frame(b = 1))
check_list(l, named = TRUE)
``` 
l passes the check. Do you think it might be a good option (or default) to check that all are named?

**Comment by joethorley** [comment]
Good question - technically all the elements are named (see below)
its just that the name of the second element is ""
```
> l <- list(a = data.frame(a = 1), data.frame(b = 1))
> check_list(l, named = TRUE)
> names(l)
[1] "a" "" 
```
I'll think about this...

**Comment by joethorley** [comment]
@sebdalgarno I'm thinking that an option to set `named = c(1L, 100L)` to require that all names are for example between 1 and 100 characters in length would be a good solution - thoughts?

**Comment by joethorley** [comment]
done and pushed to drat
```
> l <- list(a = data.frame(a = 1), data.frame(b = 1))
> check_list(l, named = TRUE)
> check_list(l, named = ".+")
 Error: names of l must match regular expression '.+' 
> check_list(l, named = c(1,2))
 Error: names of l must have at least 1 character 
```

**Comment by sebdalgarno** [comment]
that's great. Thanks for the changes!
